app/health/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import InputRequired,Length,EqualTo

class FormPost(FlaskForm):
  title = StringField('Blog Title', validators=[InputRequired(), Length(1, 64)])
  author = StringField('Author : ',)
  category = RadioField('Blog Category :', choices = [('Health', 'Health')], validators = [InputRequired()])
  content = TextAreaField('Your Post', validators=[InputRequired()])
  submit = SubmitField('Post')
  
  
class CommentForm(FlaskForm):
  content = TextAreaField('Leave a comment ...', validators=[InputRequired()])
  submit = SubmitField('Submit')

app/nutrition/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import InputRequired,Length,EqualTo

class FormPost(FlaskForm):
  title = StringField('Blog Title', validators=[InputRequired(), Length(1, 64)])
  author = StringField('Author : ',)
  category = RadioField('Blog Category :', choices = [('Nutrition', 'Nutrition')], validators = [InputRequired()])
  content = TextAreaField('Your Post', validators=[InputRequired()])
  submit = SubmitField('Post')
  
  
class CommentForm(FlaskForm):
  content = TextAreaField('Leave a comment ...', validators=[InputRequired()])
  submit = SubmitField('Submit')

app/health/__init__.py
from flask import Blueprint
health = Blueprint('health',__name__)
from . import views,forms

app/health/views.py
from . import health
from flask import render_template,redirect, request,url_for,abort,flash
from .forms import CommentForm,FormPost
from ..models import Comment,Post,User
from flask_login import login_required,current_user
from .. import db
@health.route('/health')
def index():
    title = 'Health and Wellness'
    post = Post.query.order_by(Post.date_created).all()
    return render_template('health.html', title=title, post=post)




@health.route('/createpost', methods=['GET', 'POST'])
##@login_required
def new_post():
    form = FormPost()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        new_post= Post(title=title, content=content) #user_id = currrent_user
        new_post.save_post()
        flash('Your post has been Created','Success')
        return redirect(url_for('health.index'))
    return render_template('post.html', title='New Post',form = form)

@health.route('/post/<post_id>', methods=['GET', 'POST'])
def post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    print(post)
    return render_template('contpost.html',post=post)


@health.route('/post/<post_id>/update',methods=['GET', 'POST'])
#@login_required
def update_post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    # if post.user != current_user:
    #     abort(403)

    form=FormPost()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Your post has been Updated','Success')
        return redirect(url_for('.post',post_id=post.id) )
    elif request.method=='GET':
        form.title.data=post.title
        form.content.data=post.content
        
    return render_template('post.html', form = form,title='Update Post')

@health.route('/post/<post_id>/delete',methods=['GET', 'POST'])
#@login_required
def delete_post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    # if post.user != current_user:
        # abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted successfully!','success')
    return redirect(url_for('health.index'))

@health.route('/comments/<post_id>', methods=['GET', 'POST'])
##@login_required
def comments(post_id):
    comments = Comment.query.filter_by(post_id=post_id).all()
    post = Post.query.get(post_id)
    form = CommentForm()
    if post is None:
        abort(404)
    if form.validate_on_submit():
            comment = Comment(
            content=form.content.data,
            post_id=post_id,
            # user_id=current_user.id
        )
            db.session.add(comment)
            db.session.commit()
            form.content.data = ''
            flash('Your comment has been posted successfully!','success')
    return render_template('comments.html',posts= post, comment=comments, form = form)

@health.route('/comment/<comment_id>', methods=['POST','GET'])
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id = comment_id).first()
    post_id = comment.post_id
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted successfully!','success')
    return redirect(url_for('.post',post_id = post_id))

app/nutrition/__init__.py
from flask import Blueprint
nutrition = Blueprint('nutrition',__name__)
from . import views,forms

app/nutrition/views.py
from . import nutrition
from flask import render_template,redirect, request,url_for,abort,flash
from .forms import CommentForm,FormPost
from ..models import Comment,Post,User
from flask_login import login_required,current_user
from .. import db


@nutrition.route('/nutrition')
def index():
    title = 'Nutrition'
    post = Post.query.order_by(Post.date_created).all()
    return render_template('nutrition.html', title=title, post=post)




@nutrition.route('/createpost', methods=['GET', 'POST'])
##@login_required
def new_post():
    form = FormPost()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        new_post= Post(title=title, content=content) #user_id = currrent_user
        new_post.save_post()
        flash('Your post has been Created','Success')
        return redirect(url_for('nutrition.index'))
    return render_template('post.html', title='New Post',form = form)

@nutrition.route('/post/<post_id>', methods=['GET', 'POST'])
def post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    print(post)
    return render_template('nutpost.html',post=post)


@nutrition.route('/post/<post_id>/update',methods=['GET', 'POST'])
#@login_required
def update_post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    if post.user != current_user:
        abort(403)

    form=FormPost()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Your post has been Updated','Success')
        return redirect(url_for('.post',post_id=post.id) )
    elif request.method=='GET':
        form.title.data=post.title
        form.content.data=post.content
        
    return render_template('post.html', form = form,title='Update Post')

@nutrition.route('/post/<post_id>/delete',methods=['GET', 'POST'])
#@login_required
def delete_post(post_id):
    post=Post.query.filter_by(id=post_id).first()
    if post.user != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted successfully!','success')
    return redirect(url_for('nutrition.index'))

@nutrition.route('/comments/<post_id>', methods=['GET', 'POST'])
##@login_required
def comments(post_id):
    comments = Comment.query.filter_by(post_id=post_id).all()
    post = Post.query.get(post_id)
    form = CommentForm()
    if post is None:
        abort(404)
    if form.validate_on_submit():
            comment = Comment(
            content=form.content.data,
            post_id=post_id,
            user_id=current_user.id
        )
            db.session.add(comment)
            db.session.commit()
            form.content.data = ''
            flash('Your comment has been posted successfully!','success')
    return render_template('comments.html',posts= post, comment=comments, form = form)

@nutrition.route('/comment/<comment_id>', methods=['POST','GET'])
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id = comment_id).first()
    post_id = comment.post_id
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted successfully!','success')
    return redirect(url_for('.post',post_id = post_id))

app/templates/add_post.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}


{% block content %}

    <div id="post-section"  >  
            <div class=" row" >
                    
                    <div class="col-md-2"></div>
                    <div class="col-md-8" id="postform">
                        <h2 class="text-center">Create Your Post!</h2>
                        {{wtf.quick_form(form)}}
                    </div>
                    <div class="col-md-2"></div>
            </div>
    </div>
   
{% endblock%}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Welcome to Fitness Freak, one of the most helpful health and fitness blogs.</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% endif %} {% extends 'bootstrap/base.html'%}
    
  </head>
  <body>
    {% block body %}
  <body>

  <!-- Navbar block  --> 
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock %}
    {% block styles %} {{super()}}
    <link
      href="{{url_for('static',filename='css/base.css')}}"
      rel="stylesheet"
    />
    <link
    href="{{url_for('static',filename='css/index.css')}}"
    rel="stylesheet"
  />
    {% endblock %}

     {% block content%}
     
     {%endblock%}
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;500;600;700&display=swap" rel="stylesheet">
  </body>
  {%endblock%}
</html>

app/templates/comments.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}



{% block content %}
 <body>
  <!-- <div class="jumbotron mt-3"> -->
    <div class="container">
    <h1 class="display-6 text-center">Comments</h1>
   
    </div>

  
  <div  class="container ">
    <div class="row">
      <div class="col-md-4 comt" id ="comments1">
        {{wtf.quick_form(form)}}
      </div>
   
      {% for comment in comment %}
      <div class="col-md-4">
        <div class="card bg-white"> 
          <p>Comment:<strong>{{ comment.content }}</strong></p>
            <p>Date Posted :<strong>{{ comment.date_created}}</strong></p>
              
              <a href="{{ url_for('health.delete_comment', comment_id = comment.id)}}">Delete Comment</a>
              <a href="{{ url_for('nutrition.delete_comment', comment_id = comment.id)}}">Delete Comment</a>
              <a href="{{ url_for('fitness.delete_comment', comment_id = comment.id)}}">Delete Comment</a>
            </div>
          </div>
          {% endfor %}
      </div>
    </div>
  </div>
</body>
    {% endblock%}

app/templates/contpost.html
{% extends 'base.html'%}
{% block content %}
<div class="container" id ="blogt">


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 ">
      <div class="panel panel-default text-center ">
        <div class="panel-heading">
          
          <h4 span style="font-weight: 900;"> <a href="{{url_for('health.post',post_id = post.id)}}" ></a>{{ post.title}}</h4>
          <p><b>{{ post.author }}</b></p>
        </div>
        <div class="panel-body" >
          <p>{{ post.content }}</p>
          

          <p><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">{{
                      post.date_created.strftime("%m/%d/%Y")}}</span></strong> <br>
                      <button class="btn btn-success"><a class="text" href="{{ url_for('health.comments', post_id = post.id)}}">comment</a></button>
                      <button class="btn btn-success"><a href="{{ url_for('health.update_post', post_id = post.id)}}">Edit</a></button>
                        <button class="btn btn-success"><a href="{{ url_for('health.delete_post', post_id = post.id)}}">Delete post</a></button>

          </p>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

app/templates/fitness.html
{% extends 'base.html'%} 
{% block body %}  
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock %}
{% block styles %} {{super()}}
<link
  href="{{url_for('static',filename='css/fitness.css')}}"
  rel="stylesheet"/>
{% endblock %}
{% block content%}


<div class="card container ">
    <div class="card-body">
      <h5 class="card-title hed1"> Fitness
        </h5>
        <p>"When it comes to eating right and exercising,  there is no I'll start tomorrow"</p>
    </div>

    <div class="container cont1">
        <div class="row">
         
          <div class="col-md-5 mind">
             <h1 class="header text-center">Cardiovascular Endurance</h1>

             <p>This is the ability of the heart and lungs to work together to provide the needed oxygen and fuel to the body during sustained workloads. Examples would be jogging, cycling and swimming. The Cooper Run is used most often to test cardiovascular endurance.</p>
          </div>
          <div class="col-md-1"> </div>
          <div class="col-md-6 diet">
            <h1 class="header text-center">Muscular endurance</h1>
            <p>
              This is the ability of the muscles to perform continuous without fatiguing. Examples would be cycling, step machines and elliptical machines. The sit up test is most often used to test muscular endurance
            </p>
          </div>
        </div>
       
      </div>
  </div>
  <div>
    
  </div>
  {% for post in post %}
  <div class="container postt">
    <h2 class="card-subtitle mb-2 text-muted"><a href="{{url_for('fitness.post',post_id = post.id)}}" >{{ post.title}}</a></h2>
    <p>{{ post.content|safe }}</p>
    <p><b>{{ post.author }}</b></p>
    <p class="panel-text"><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">
      {{ post.date_created.strftime("%m/%d/%Y")}}</span></strong> </p>
      <p><a href="{{ url_for('fitness.comments', post_id = post.id)}}">Comment</a> {{post.comment.count()}} Comments</p>
  </div>
  {% endfor %}

  {% endblock%}


{% endblock%}

app/templates/health.html
{% extends 'base.html'%} 
{% block body %}
  <!-- Navbar block  --> 
  {% block navbar %}
  {% include 'navbar.html' %}
  {% endblock %}
{% block styles %} {{super()}}
<link
  href="{{url_for('static',filename='css/base.css')}}"
  rel="stylesheet"
/>
{% endblock %}
{% block content%}
<h1 class="header text-center">Health</h1>

<div class="card container ">
    <div class="card-body">
      <h5 class="card-title hed1">
        “Our Food Should Be Our Medicine && Our Medicine Should Be Our Food”</h5>
    </div>



    <div class="container cont1">
        <div class="row">
         
          <div class="col-md-5 mind">
             <h1 class="header text-center">Mind and Body</h1>

             <p>The mind and body are said to be two different entities that have different characteristics. Many have argued that each holds its own properties and can be without the other. In my opinion, the mind and body are distinguishable in there properties but are derived from the other. The mind and body are codependent on each other and need the other in making decisions. The mind requires the body to learn, experience so as to make accurate judgments, while the body requires the mind to make its decisions for it. Without one or the other, I feel they would not be able to exist.

                The mind and the body coexist together and thrive on the other by using the others traits</p>
          </div>
          <div class="col-md-1"> </div>
          <div class="col-md-6 diet">
            <h1 class="header text-center">Diet</h1>
            <p>
                A healthy diet is a balance of being able to supply your body with the right nutrients. The five essential nutrients are proteins, fats, minerals, carbohydrates, also water and fibre. A healthy diet is crucial for maintaining the health and wellbeing of your body. Eating healthy can also aid to reduce chronic diseases such as type two Diabetes, Heart conditions and certain cancers). According to the Australian dietary guidelines One-third of Australian premature deaths from diseases have been mostly linked to obesity it also has been predicted that by 2023 type two diabetes will be Australia’s ‘biggest disease burden’. A healthy diet is fundamental to the health and fitness 
            </p>
          </div>
        </div>
      </div>
  </div>
  <div>
    
  </div>
  {% for post in post %}
  <div class="container postt">
    <h2 class="card-subtitle mb-2 text-muted"><a href="{{url_for('health.post',post_id = post.id)}}" >{{ post.title}}</a></h2>
    <p>{{ post.content|safe }}</p>
    <p><b>{{ post.author }}</b></p>
    <p class="panel-text"><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">
      {{ post.date_created.strftime("%m/%d/%Y")}}</span></strong> </p>
      <a href="{{ url_for('health.comments', post_id = post.id)}}">comment</a>
  </div>
  {% endfor %}

  {% endblock%}


{% endblock%}

app/templates/index.html
{% extends 'base.html'%} 

{% block content%}

  <!-- Main Content -->
 
  <body>
    <header class="landing"> <h1>Welcome to <br> Fitness Freak</h1></header>
      <div class="container">
        <div class="card">
          <div class="card-body">
            <h4 class="card-text text-center"><br>Whether you want to tone up,build muscle, or set a new personal record, Fitness Freak can help you achieve your goal.<br>
            <br>Fitness Freak has everything you want not just for fitness, but for holistic, real-talk wellness.<br>
            <br>Its the target of wellness apps-it has a little bit of everything.<br>
            <br>It is designed for those who frequently sit and experience tense muscles. Slower and faster-paced excercises allow your 
            body to unwind after a long working day.<br>  
            </h4>
          </div>
        </div>
      </div>
    </div>
    {% endblock%}
  </body>

app/templates/loggedin.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block styles %}
    {{ super() }}
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/login.css')}}" type="text/css">

    {% endblock %}
</head>
<body>
            <!-- Navbar block  --> 
        {% block navbar %}
        {% include 'navbar.html' %}
        {% endblock %}  

        {% block content %}
       
    {% endblock %}
</body>
</html>

app/templates/macros.html
{% extends 'bootstrap/base.html'%}
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}
{% macro display(category_list) %}
<div class="row">
	{% if category_list %}
        {% for category in category_list %}
       
        <div class="col-md-4">
            <div class="panel panel-default" >
                <div class="panel-heading" style="height: 30px; padding-top: 2px; font-weight: bolder; text-transform: uppercase; color: rgb(184, 76, 37);" >
                    {{category.title}} {{category.category}}
                </div>
                <div class="panel-body" style="background-color:#faf5f5;">
                  <p style="color: black; font-size: 12px;">
                    {{category.description}}
                  </p>
             </div>                   
            </div>
        
        </div>
       
		{% endfor %}
	{% else %}
	{% endif %}
</div>
{% endmacro %}

app/templates/navbar.html
<header class="header">
  <div class="container header-nav">
    <div class="logo-box">
      <img src="" height="50">
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark width=1">
      {% if current_user.is_authenticated %}
    <ul>
      <li class="nav-item"><a class="nav-link" href="/" style="font-size:15px;">Home</a></li>
      <li class="nav-item"><a class="nav-link" href="/health"  style="font-size:15px;">Health</a></li>
      <li class="nav-item"><a class="nav-link" href="/fitness"  style="font-size:15px;">Fitness</a></li>
      <li class="nav-item"><a class="nav-link" href="/nutrition"  style="font-size:15px;">Nutrition</a></li>
      <li class="nav-item"><a class="nav-link" href="{{url_for('auth.logout')}}" style="font-size:15px;">Sign out</a></li>

      {% else %}
      <li><a href="{{url_for('auth.login')}}" style="font-size:20px;">Log in</a></li>
   </ul>
   {%endif%}
 
  </div>
</nav>
</header>

app/templates/nutpost.html
  
{% extends 'base.html'%}
{% block content %}
<div class="container" id ="nutpost">


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 ">
      <div class="panel panel-default text-center ">
        <div class="panel-heading">
          
          <h4 span style="font-weight: 900;"> <a href="{{url_for('nutrition.post',post_id = post.id)}}" ></a>{{ post.title}}</h4>
          <p><b>{{ post.author }}</b></p>
        </div>
        <div class="panel-body" >
          <p>{{ post.content }}</p>
          

          <p><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">{{
                      post.date_created.strftime("%m/%d/%Y")}}</span></strong> <br>
                      <button class="btn btn-success"><a class="text" href="{{ url_for('nutrition.comments', post_id = post.id)}}">comment</a></button>
                      <button class="btn btn-success"><a href="{{ url_for('nutrition.update_post', post_id = post.id)}}">Edit</a></button>
                        <button class="btn btn-success"><a href="{{ url_for('nutrition.delete_post', post_id = post.id)}}">Delete post</a></button>

          </p>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

app/templates/nutrition.html
{% extends 'base.html'%} 
{% block content%}
<h1 class="header text-center">Nutrition</h1>

<div class="card container ">
    <div class="card-body">
      <p class="card-title heading1">
        “Nutrition is the process of consuming absorbing and using nutrients needed by the body for growth, development and maintenance of life. To receive adequate, appropriate nutrition, people need to consume a healthy diet which consists of a variety of nutrients-the substances in food that nourish the body.”</p>
    </div>



    <div class="container cont1">
        <div class="row">
         
          <div class="col-md-5 vitamins">
             <h1 class="header text-center">Vitamins</h1>

             <p> Consuming vitamins help you resist infections as well as keep your nerves healthy. Some vitamins may help your body get energy from food or even help your blood clot properly.</p>
          </div>
          <div class="col-md-1"> </div>
          <div class="col-md-6 proteins">
            
            <h1 class="header text-center">Proteins</h1>
            <p>
                Proteins rebuild your muscle tissues after exercise and also plays a minor role in producing energy under more extreme training conditions. The complete proteins we consume (e.g. meats, fish, dairy, eggs, etc.) are made up of the same amino acids that make up our muscles.
            </p>
            
          </div>
          
          
          <div class="col-md-5 carbohydrates">
              <h1 class="header text center">Carbohydrates</h1>
              <p>Consuming dietary carbohydrate soon after exercise results in faster rates of glycogen re-synthesis and provides the body with enough glucose to initiate the recovery process.</p>

          </div>
          <div class="col-md-1"></div>
          <div class="col-md-6 water">
            <h1 class="header text center">Water</h1>
            <p>Water regulates your body temperature and lubricates your joints. It helps transport nutrients to give you energy and keep you healthy. If you're not hydrated, your body can't perform at its highest level and you may feel tired.</p>

          </div>
        </div>
      </div>
  </div>
  <h1 class="header text-center">Contact a Nutritionist</h1>
  <div class="card container">
      <div class="card body">
            <h5>Charity Nyange</h5>
            <h6>PO Box 80072-80100, Mombasa</h6>
            <h6>Tel: 0202101206</h6>
            <h6>Email: info@.ackpwaniccs.or.ke</h6>
         

          </div>

      </div>

  </div> 
    
  
  {% for post in post %}
  <div class="container postt">
    <h2 class="card-subtitle mb-2 text-muted"><a href="{{url_for('nutrition.post',post_id = post.id)}}" >{{ post.title}}</a></h2>
    <p>{{ post.content|safe }}</p>
    <p><b>{{ post.author }}</b></p>
    <p class="panel-text"><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">
      {{ post.date_created.strftime("%m/%d/%Y")}}</span></strong> </p>
      <a href="{{ url_for('nutrition.comments', post_id = post.id)}}">comment</a>
  </div>
  {% endfor %}





{% endblock%}

app/templates/post.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content %}
 <body>
  <div  class="container blg">
        
      <div class="row">
      <div class="col-md-12 ">
         
          {{wtf.quick_form(form)}}
      </div>
    </div>
</div>
 </body> 
 {%endblock%}
  </div>

app/templates/showpost.html
{% extends 'base.html'%}
{% block content %}
<div class="container">


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6 ">
      <div class="panel panel-default text-center ">
        <div class="panel-heading">
          
          <h4 span style="font-weight: 900;"> <a href="{{url_for('fitness.post',post_id = post.id)}}" ></a>{{ post.title}}</h4>
          <p><b>{{ post.author }}</b></p>
        </div>
        <div class="panel-body" >
          <p>{{ post.content }}</p>
          

          <p><strong>Created on: <span class="badge rounded-pill bg-warning text-dark">{{
                      post.date_created.strftime("%m/%d/%Y")}}</span></strong> <br>
                      <button class="btn btn-success"><a class="text" href="{{ url_for('fitness.comments', post_id = post.id)}}">comment</a></button>
                      <button class="btn btn-success"><a href="{{ url_for('fitness.update_post', post_id = post.id)}}">Edit</a></button>
                        <button class="btn btn-success"><a href="{{ url_for('fitness.delete_post', post_id = post.id)}}">Delete post</a></button>

          </p>

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}